version: '3.8'

services:
  db:
    image: postgres
    container_name: pgdb-e-shop
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    build:
      context: ./
      dockerfile: ./dockerfiles/django/Dockerfile
      args:
        - DEV=${DEV}
    container_name: django
    # Change env_file to ./.env in production:
    env_file:
      - ./.dev.env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
volumes:
  postgres_data:
