# pylint: disable=protected-access
# pylint: disable=no-self-argument
# pylint: disable=invalid-name

"""Contains factories for order related models."""
from random import choice
from datetime import datetime
from factory.django import DjangoModelFactory
from factory import Faker, sequence, lazy_attribute
from django.contrib.auth import get_user_model

from ..accounts.factories import UserFactory
from .models import Status, Order, OrderItem
from ..products.models import Product
from ..products.factories import ProductFactory


class StatusFactory(DjangoModelFactory):
    """Order status Factory for Status model."""

    class Meta:
        model = Status

    @sequence
    def name(n):
        """Add the 'name' field, which is generated by default with a unique value."""
        while True:
            name = Faker("word")._get_faker().word()
            try:
                _ = Status.objects.get(name=name)
                continue
            except Status.DoesNotExist:
                return name


class OrderFactory(DjangoModelFactory):
    """Order Factory for Order model."""

    class Meta:
        model = Order

    date_time_updated = Faker(
        "date_between_dates",
        date_start=datetime(2000, 1, 1),
        date_end=datetime(2022, 1, 1),
    )

    @lazy_attribute
    def customer(self):
        """
        Add the 'customer' field, which is generated by default with a
        pointer to the random existing User model or a new one.
        """
        try:
            return choice(tuple(get_user_model().objects.all()))
        except IndexError:
            return UserFactory.create()

    @lazy_attribute
    def status(self):
        """
        Add the 'status' field, which is generated by default with a
        pointer to the random existing Status model or a new one.
        """
        try:
            return choice(tuple(Status.objects.all()))
        except IndexError:
            return StatusFactory.create()


class OrderItemFactory(DjangoModelFactory):
    """OrderItem Factory for OrderItem model."""

    class Meta:
        model = OrderItem

    quantity = Faker("random_int")
    date_time_added = Faker(
        "date_between_dates",
        date_start=datetime(2000, 1, 1),
        date_end=datetime(2022, 1, 1),
    )

    @lazy_attribute
    def order(self):
        """
        Add the 'order' field, which is generated by default with a
        pointer to the random existing Order model or a new one.
        """
        try:
            return choice(tuple(Order.objects.all()))
        except IndexError:
            return OrderFactory.create()

    @lazy_attribute
    def product(self):
        """
        Add the 'product' field, which is generated by default with a
        pointer to the random existing Product model or a new one.
        """
        try:
            return choice(tuple(Product.objects.all()))
        except IndexError:
            return ProductFactory.create()
