name: Test & lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: docker-compose --env-file .dev.env run --rm django sh -c "python manage.py wait_for_db && pytest"
        - name: Lint
          run: >
            docker-compose --env-file .dev.env run --rm django sh -c
            "pylint src
            --rcfile=/app/.pylintrc
            --load-plugins pylint_django
            --django-settings-module=config.settings
            --output-format=colorized"